import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_serialization: String = "0.14.0"

    const val io_gitlab_arturbosch_detekt: String = "1.3.0"

    const val com_github_bumptech_glide: String = "4.10.0"

    const val androidx_test_espresso: String = "3.2.0"

    const val com_louiscad_splitties: String = "3.0.0-alpha06"

    const val com_squareup_retrofit2: String = "2.7.0"

    const val com_squareup_okhttp3: String = "4.2.2"

    const val org_jetbrains_kotlin: String = "1.3.61"

    const val androidx_navigation: String = "2.1.0"

    const val com_squareup_inject: String = "0.5.2"

    const val androidx_arch_core: String = "2.1.0"

    const val androidx_lifecycle: String = "2.2.0-rc03"

    const val com_google_dagger: String = "2.25.4"

    const val androidx_room: String = "2.2.3"

    const val androidx_test: String = "1.2.0"

    const val org_mockito: String = "3.2.4"

    const val com_android_tools_build_gradle: String = "3.6.0-rc01"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val io_fabric_tools_gradle: String = "1.31.2"

    const val junit_junit: String = "4.12"

    const val org_jetbrains_kotlin_android_extensions_gradle_plugin: String = "1.3.61"

    const val org_jetbrains_kotlin_android_gradle_plugin: String = "1.3.61"

    const val retrofit2_kotlinx_serialization_converter: String = "0.4.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val org_jetbrains_kotlin_kapt_gradle_plugin: String = "1.3.61"

    const val com_github_spotbugs_gradle_plugin: String = "3.0.0"

    const val kotlintest_runner_junit4: String = "3.4.2"

    const val findsecbugs_plugin: String = "1.10.1"

    const val firebase_analytics: String = "17.2.1"

    const val firebase_messaging: String = "20.1.0"

    const val facebook_applinks: String = "4.42.0" // available: "5.13.0"

    const val constraintlayout: String = "1.1.3"

    const val epoxy_processor: String = "3.9.0"

    const val google_services: String = "4.3.3"

    const val equalsverifier: String = "3.1.11"

    const val kotlin_logging: String = "1.7.8"

    const val preference_ktx: String = "1.1.0"

    const val shortcutbadger: String = "1.1.22"

    const val vectordrawable: String = "1.1.0"

    const val exifinterface: String = "1.1.0"

    const val firebase_core: String = "17.2.1"

    const val slf4j_android: String = "1.7.30-0"

    const val assertj_core: String = "3.14.0"

    const val fragment_ktx: String = "1.2.0-rc04"

    const val recyclerview: String = "1.1.0"

    const val billing_ktx: String = "2.1.0"

    const val crashlytics: String = "2.10.1"

    const val lint_gradle: String = "26.6.0-rc01"

    const val slf4j_jdk14: String = "1.7.30"

    const val threetenabp: String = "1.2.1"

    const val annotation: String = "1.1.0"

    const val sb_contrib: String = "7.4.7"

    const val appcompat: String = "1.1.0"

    const val rxandroid: String = "2.1.1"

    const val cardview: String = "1.0.0"

    const val core_ktx: String = "1.1.0"

    const val material: String = "1.0.0"

    const val rxkotlin: String = "2.4.0"

    const val spotbugs: String = "3.1.12"

    const val rxjava: String = "2.2.16"

    const val aapt2: String = "3.6.0-rc01-6040484"

    const val epoxy: String = "3.9.0"

    const val mvrx: String = "1.3.0"

    /**
     * Current version: "6.0.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.0.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
        id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
